// Code generated by ent, DO NOT EDIT.

package employees

const (
	// Label holds the string label denoting the employees type in the database.
	Label = "employees"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// Table holds the table name of the employees in the database.
	Table = "employees"
)

// Columns holds all SQL columns for employees fields.
var Columns = []string{
	FieldID,
	FieldGender,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	GenderValidator func(string) error
)
