// Code generated by mockery v2.24.0. DO NOT EDIT.

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIEmployeeService is an autogenerated mock type for the IEmployeeService type
type MockIEmployeeService struct {
	mock.Mock
}

type MockIEmployeeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEmployeeService) EXPECT() *MockIEmployeeService_Expecter {
	return &MockIEmployeeService_Expecter{mock: &_m.Mock}
}

// AddEmployee provides a mock function with given fields: c, gender
func (_m *MockIEmployeeService) AddEmployee(c context.Context, gender string) (int, error) {
	ret := _m.Called(c, gender)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(c, gender)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(c, gender)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, gender)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEmployeeService_AddEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEmployee'
type MockIEmployeeService_AddEmployee_Call struct {
	*mock.Call
}

// AddEmployee is a helper method to define mock.On call
//   - c context.Context
//   - gender string
func (_e *MockIEmployeeService_Expecter) AddEmployee(c interface{}, gender interface{}) *MockIEmployeeService_AddEmployee_Call {
	return &MockIEmployeeService_AddEmployee_Call{Call: _e.mock.On("AddEmployee", c, gender)}
}

func (_c *MockIEmployeeService_AddEmployee_Call) Run(run func(c context.Context, gender string)) *MockIEmployeeService_AddEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIEmployeeService_AddEmployee_Call) Return(_a0 int, _a1 error) *MockIEmployeeService_AddEmployee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEmployeeService_AddEmployee_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockIEmployeeService_AddEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveAllEmployees provides a mock function with given fields: c
func (_m *MockIEmployeeService) RetrieveAllEmployees(c context.Context) ([]Employee, error) {
	ret := _m.Called(c)

	var r0 []Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]Employee, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []Employee); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEmployeeService_RetrieveAllEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveAllEmployees'
type MockIEmployeeService_RetrieveAllEmployees_Call struct {
	*mock.Call
}

// RetrieveAllEmployees is a helper method to define mock.On call
//   - c context.Context
func (_e *MockIEmployeeService_Expecter) RetrieveAllEmployees(c interface{}) *MockIEmployeeService_RetrieveAllEmployees_Call {
	return &MockIEmployeeService_RetrieveAllEmployees_Call{Call: _e.mock.On("RetrieveAllEmployees", c)}
}

func (_c *MockIEmployeeService_RetrieveAllEmployees_Call) Run(run func(c context.Context)) *MockIEmployeeService_RetrieveAllEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIEmployeeService_RetrieveAllEmployees_Call) Return(_a0 []Employee, _a1 error) *MockIEmployeeService_RetrieveAllEmployees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEmployeeService_RetrieveAllEmployees_Call) RunAndReturn(run func(context.Context) ([]Employee, error)) *MockIEmployeeService_RetrieveAllEmployees_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockIEmployeeService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIEmployeeService creates a new instance of MockIEmployeeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIEmployeeService(t mockConstructorTestingTNewMockIEmployeeService) *MockIEmployeeService {
	mock := &MockIEmployeeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
