// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"go.uber.org/zap"
	"golang-api/ent"
	"golang-api/internal/config"
	"golang-api/internal/core"
	"golang-api/internal/infra"
	"golang-api/internal/web"
)

// Injectors from wire.go:

// InitializeServer - initialize the server
func InitializeServer(config2 config.Config, client *ent.Client, logger *zap.Logger) (*web.Server, error) {
	employeeMapper := infra.NewEmployeeMapper()
	employeeRepository := infra.NewEmployeeRepository(client, employeeMapper)
	employeeService := core.NewEmployeeService(employeeRepository)
	employeeHandler := web.NewEmployeeHandler(employeeService)
	healthCheckHandler := web.NewHealthCheckHandler()
	server := web.NewServer(logger, config2, employeeHandler, healthCheckHandler)
	return server, nil
}
