// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"golang-api/ent"
	"golang-api/internal/config"
	"golang-api/internal/core"
	"golang-api/internal/infra"
	"golang-api/internal/web"
)

// Injectors from wire.go:

// InitializeServer - initialize the server
func InitializeServer(config2 config.Config, client *ent.Client) (*web.Server, error) {
	employeeMapper := infra.NewEmployeeMapper()
	employeeRepository := infra.NewEmployeeRepository(client, employeeMapper)
	employeeService := core.NewEmployeeService(employeeRepository)
	employeeHandler := web.NewEmployeeHandler(employeeService)
	server := web.NewServer(config2, employeeHandler)
	return server, nil
}
