// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"golang-api/ent/migrate"

	"golang-api/ent/employees"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Employees is the client for interacting with the Employees builders.
	Employees *EmployeesClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Employees = NewEmployeesClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Employees: NewEmployeesClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Employees: NewEmployeesClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Employees.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Employees.Use(hooks...)
}

// EmployeesClient is a client for the Employees schema.
type EmployeesClient struct {
	config
}

// NewEmployeesClient returns a client for the Employees from the given config.
func NewEmployeesClient(c config) *EmployeesClient {
	return &EmployeesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employees.Hooks(f(g(h())))`.
func (c *EmployeesClient) Use(hooks ...Hook) {
	c.hooks.Employees = append(c.hooks.Employees, hooks...)
}

// Create returns a builder for creating a Employees entity.
func (c *EmployeesClient) Create() *EmployeesCreate {
	mutation := newEmployeesMutation(c.config, OpCreate)
	return &EmployeesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Employees entities.
func (c *EmployeesClient) CreateBulk(builders ...*EmployeesCreate) *EmployeesCreateBulk {
	return &EmployeesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Employees.
func (c *EmployeesClient) Update() *EmployeesUpdate {
	mutation := newEmployeesMutation(c.config, OpUpdate)
	return &EmployeesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmployeesClient) UpdateOne(e *Employees) *EmployeesUpdateOne {
	mutation := newEmployeesMutation(c.config, OpUpdateOne, withEmployees(e))
	return &EmployeesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmployeesClient) UpdateOneID(id int) *EmployeesUpdateOne {
	mutation := newEmployeesMutation(c.config, OpUpdateOne, withEmployeesID(id))
	return &EmployeesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Employees.
func (c *EmployeesClient) Delete() *EmployeesDelete {
	mutation := newEmployeesMutation(c.config, OpDelete)
	return &EmployeesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmployeesClient) DeleteOne(e *Employees) *EmployeesDeleteOne {
	return c.DeleteOneID(e.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *EmployeesClient) DeleteOneID(id int) *EmployeesDeleteOne {
	builder := c.Delete().Where(employees.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmployeesDeleteOne{builder}
}

// Query returns a query builder for Employees.
func (c *EmployeesClient) Query() *EmployeesQuery {
	return &EmployeesQuery{
		config: c.config,
	}
}

// Get returns a Employees entity by its id.
func (c *EmployeesClient) Get(ctx context.Context, id int) (*Employees, error) {
	return c.Query().Where(employees.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmployeesClient) GetX(ctx context.Context, id int) *Employees {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmployeesClient) Hooks() []Hook {
	return c.hooks.Employees
}
