// Code generated by ent, DO NOT EDIT.

package ent

import (
	"golang-api/ent/employees"
	"golang-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employeesFields := schema.Employees{}.Fields()
	_ = employeesFields
	// employeesDescGender is the schema descriptor for gender field.
	employeesDescGender := employeesFields[0].Descriptor()
	// employees.GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	employees.GenderValidator = employeesDescGender.Validators[0].(func(string) error)
}
